# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 700757ea6c2e74b8b985b514f0d79a30611c4774fed0f37dd4f26b632bedba095a023c7f3a6b593cd8dc24c8c691e67b0c7128a1352997287f7051f7ba36ef8b

test:
  secret_key_base: 00a13241cf8aa451cac05253a1aaa74c6b3515967f67bfd36ed77bbba584d5da50316340c90c15e4bfb95b119e0c04831b95c62bbf27391d8fd97febf7cab548

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
